import { Fira_Code } from "next/font/google";

import Header from "../components/Header.jsx";
import Footer from "../components/Footer.jsx";

import "./globals.css"

const fira_code = Fira_Code({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: "--font-fira-code",
  display: "swap",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-screen h-screen p-4 bg-black ${fira_code.className} text-light-text`}>
        <main className='flex flex-col w-full h-full bg-main-bg border border-border-color rounded-lg'>
          <Header />
          <section className="grow">
            {children}
          </section>
          <Footer />
        </main>
      </body>
    </html>
  )
}
